name: ${project.name}
version: ${project.version}
main: me.messageofdeath.commandnpc.CommandNPC

author: messageofdeath

depend: [Citizens]
softdepend: [Vault]
commands:
  commandnpc:
    description: Reload this plugin.