name: CommandNPC
author: messageofdeath
version: 1.9.1
main: me.messageofdeath.commandnpc.CommandNPC
depend: [Citizens]
softdepend: [Vault, PlaceholderAPI]
commands:
  commandnpc:
    description: Reload this plugin.
