name: CommandNPC
author: messageofdeath
version: 1.8.9
main: me.messageofdeath.commandnpc.CommandNPC
depend: [Citizens]
softdepend: [Vault]
commands:
  commandnpc:
    description: Reload this plugin.