name: CommandNPC
author: messageofdeath
version: 1.8.8
main: me.messageofdeath.CommandNPC.CommandNPC
depend: [Citizens]
softdepend: [Vault]
commands:
  commandnpc:
    description: Reload this plugin.